name: First workflow

on: [push, pull_request]

jobs:

  build:

    runs-on: ${{ matrix.operating-system}}

    strategy:

      matrix:

        operating-system: ['ubuntu-latest', 'windows-latest', 'macos-latest']

        php-versions: ['7.2', '7.3', '7.4']

    name: ${{ matrix.operating-system }} PHP ${{ matrix.php-versions}}

    steps:

      - uses: actions/checkout@v2

      - name: Hello Codeliesss

        run: echo "Hola desde ${{ github.workflow }} y el evento ${{ github.event_name }}"

      - name: Hola amigo

        env:

          JOB_CONTEXT: ${{ toJson(job) }}

        run: |
            echo "el job context es el siguiente $JOB_CONTEXT "
            echo "se realizó"

      - name: Greeting if Windows
        
        if: matrix.operating-system == 'windows-latest'

        run: echo "Hey from Windows"


      
      - name: Setup PHP

        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          coverage: none

      


