name: First workflow

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@mibrazo

      - name: Hello Codeliesss

        run: echo "Hola desde ${{ github.workflow }} y el evento ${{ github.event_name }}"