name: First workflow

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v1

      - name: Hello Codeliesss

        run: echo "Hola desde ${{ github.workflow }} y el evento ${{ github.event_name }}"

      - name: Hola amigo

        env:

          JOB_CONTEXT: ${{ toJson(job) }}

          run: |

            echo "el job context es el siguiente $JOB_CONTEXT "
            echo "se realizó"